
server:  port: 8085
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kafka.streams:
  binder.configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  bindings.input.consumer.application-id: tweet-service
spring.cloud.stream.bindings.output:
  destination: character_count
spring.cloud.stream.bindings.input:
  destination: marvel_dc_tweets            