
server.port: 8086
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000

spring.cloud.stream.kafka.streams:
  binder.configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$LongSerde
  bindings.input.consumer.application-id: marvel-dc-service

spring.cloud.stream.bindings.output:
  destination: comics_result

spring.cloud.stream.bindings.input:
  destination: character_count            