server.port: 8081
#spring.cloud.stream.kafka.binder.auto-create-topics=true
spring.cloud.stream.bindings.sampleMessageChannel.destination: sample_topic
spring.cloud.stream.bindings.input.destination: input

spring.cloud.stream.kafka.streams:
  binder.configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            
            
        